from django.db import models
from django.utils.timezone import now
import datetime
# Create your models here.
class ParkingManagers(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    national_code = models.CharField(max_length=10)
    tel_number = models.CharField(max_length=11)
    email = models.EmailField(max_length=100)
    date_of_birth = models.DateField()
    parking_id = models.IntegerField()
    income = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    photo_of_business_license = models.CharField(max_length=1000)
    photo_of_national_code = models.CharField(max_length=1000)
    bank_information = models.CharField(max_length=500)
    tax_returns = models.CharField(max_length=100)
    parking_capacity = models.IntegerField(null=True)
    parking_capacity_now = models.IntegerField(default=0,null=True)
    def __str__(self):
        return str(self.id) + " " +self.firstname + " " + self.lastname
class User(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    national_code = models.CharField(max_length=10)
    tel_number = models.CharField(max_length=11)
    email = models.EmailField(max_length=100)
    date_of_birth = models.DateField()
    car_tag_1 = models.CharField(max_length=2)
    car_tag_2 = models.CharField(max_length=1)
    car_tag_3 = models.CharField(max_length=3)
    car_tag_4 = models.CharField(max_length=2)
    status = models.BooleanField()
    def __str__(self):
        return str(self.id) + " " +self.firstname + " " + self.lastname
class ParkingsLists(models.Model):
    id = models.AutoField(primary_key=True)
    parking_name = models.CharField(max_length=255)
    parking_name_pr = models.CharField(max_length=255)
    parking_image = models.CharField(max_length=255)
    parking_location = models.CharField(max_length=255)
    parking_routing_link = models.CharField(max_length=255,null=True)
    parking_like = models.IntegerField(null=True)
    parking_tariff = models.IntegerField(null=True)
    atue_code = models.CharField(max_length=255,null=True)
    def __str__(self):
        return str(self.id) + " " + self.parking_name + " " + self.parking_name_pr
class Logins(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.IntegerField()
    parking_id = models.IntegerField()
    login_time = models.TimeField(null=True)
    login_date = models.DateField(null=True)
    qr_code = models.CharField(max_length=200)
    status = models.BooleanField(null=True)
class Exits(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.IntegerField()
    parking_id = models.IntegerField()
    login_id = models.IntegerField(null=True)
    exit_time = models.TimeField(null=True)
    exit_date = models.DateField(null=True)
    qr_code = models.CharField(max_length=200)
    length_of_stay = models.IntegerField(null=True)
    price = models.IntegerField(null=True)
    status = models.BooleanField(null=True)
class Pays(models.Model):
    description = models.CharField(max_length=250)
    name_of_port = models.CharField(max_length=250)
    issue_tricking = models.CharField(max_length=9)
    time = models.DateField()
    price = models.IntegerField()
    user_id = models.IntegerField()
    parking_id = models.IntegerField()
    login_id = models.IntegerField()
    exit_id = models.IntegerField()
class Requests(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    national_code = models.CharField(max_length=10)
    tel_number = models.CharField(max_length=11)
    email = models.EmailField(max_length=100)
    date_of_birth = models.DateField()
    photo_of_business_license = models.CharField(max_length=1000)
    photo_of_national_code = models.CharField(max_length=1000)
    bank_information = models.CharField(max_length=500)
    tax_returns = models.CharField(max_length=100)
    parking_name = models.CharField(max_length=255)
    parking_name_pr = models.CharField(max_length=255)
    parking_location = models.CharField(max_length=255)
    parking_tariff = models.IntegerField()
    parking_capacity = models.IntegerField(null=True)